trigger:
  - manual

jobs:
  - job: Job1
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        displayName: Checkout GitHub Repository

      - script: foo=`grep 'versionName' $(Root)app/build.gradle | tr '"' ' ' | tr 'versionName' ' '`
                echo "##vso[task.setvariable variable=two;isOutput=true]$foo"

      - script: echo $(two)
