trigger:
  - manual


steps:
  - checkout: self
    persistCredentials: true

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'

  - task: AndroidSigning@2
    inputs:
      apkFiles: '/home/vsts/work/1/s/app/build/outputs/apk/debug/*.apk'
      jarsign: true
      jarsignerKeystoreFile: 'duu_whang_keystore.keystore' #'my-release-key.keystore'
      jarsignerKeystorePassword: 'o1XAq8yvVEtbqrsLMypFYH5H' #'ddlhau8u'
      jarsignerKeystoreAlias: 'duu_whang_release_key' #'alias_name'
      jarsignerKeyPassword: 'b2dobCJrk2fN3CSWUDlNeYe7' #'681Nz0o2'
      jarsignerArguments: '-verbose -sigalg SHA256withECDSA'
      zipalign: true

  - task: CopyFiles@2
    inputs:
      sourceFolder: '/home/vsts/work/1/s/app/build/outputs/apk/debug/'
      Contents: '*.apk'
      TargetFolder: '/'
      OverWrite: true

  - task: CmdLine@2
    inputs:
      script: 'git config user.email "maxipulstorm@aon.at";
              git config user.name "duuwhang";
              git checkout master;
              git status;
              git add .;
              git commit -m "CD commit";
              git push origin;
              git status'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github.com_duuwhang
      repositoryName: '$(Build.Repository.Name)' 
      action: 'create' # Options: create, edit, delete
      target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: 'auto' # Required when action == Create# Options: auto, manual
      #tagPattern: # Optional
      #tag: # Required when action == Edit || Action == Delete || TagSource == Manual
      #title: # Optional
      #releaseNotesSource: 'file' # Optional. Options: file, input
      #releaseNotesFile: # Optional
      #releaseNotes: # Optional
      #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
      #assetUploadMode: 'delete' # Optional. Options: delete, replace
      #isDraft: false # Optional
      #isPreRelease: false # Optional
      #addChangeLog: true # Optional
      #compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
      #releaseTag: # Required when compareWith == LastReleaseByTag