name: $(Rev:_r)

trigger:
  - manual

jobs:
  - job: AndroidTestCIPipeline
    steps:
      - checkout: self
        displayName: Checkout GitHub Repository
        clean: true
        persistCredentials: true

  - job: AndroidReleaseCDPipeline
    steps:
      - checkout: self
        displayName: Checkout GitHub Repository
        clean: true
        persistCredentials: true

      - script: |
          echo "##vso[task.setvariable variable=Version]`grep 'versionName' $(Root)/app/build.gradle | tr '"' ' ' | tr 'versionName' ' '| sed 's/ //g'`"
        displayName: Read Release Version

      - script: |
          echo "##vso[build.updatebuildnumber]$(Version)$(Build.BuildNumber)"
          echo "##vso[task.setvariable variable=Condition]$[counter(variables['Version'], 0)]"
        displayName: Read Release Version2

      - task: Gradle@2
        displayName: Gradle Build Release APK
        condition: eq(variables['Condition'], 0)
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleRelease'
          options: '--no-daemon'

      - task: AndroidSigning@2
        displayName: Sign APK
        inputs:
          apkFiles: '$(Root)$(ReleaseDirectory)/*.apk'
          jarsign: true
          jarsignerKeystoreFile: 'duu_whang_keystore.keystore'
          jarsignerKeystorePassword: '$(Release.Keystore.Password)'
          jarsignerKeystoreAlias: 'duu_whang_release_key'
          jarsignerKeyPassword: '$(Release.Key.Password)'
          jarsignerArguments: '-verbose -sigalg SHA256withECDSA'
          zipalign: true

      - task: CopyFiles@2
        displayName: Copy APK to Root
        inputs:
          sourceFolder: '$(Root)$(ReleaseDirectory)/'
          Contents: '*.apk'
          TargetFolder: '$(Root)/'
          OverWrite: true

      - script: |
          git config user.email "maxipulstorm@aon.at"
          git config user.name "duuwhang"
          git checkout master
          git add .
          git commit -m "CD commit"
          git push origin
          git tag $(Version)
          git push origin --tags
        displayName: Commit APK to GitHub Repository

      - task: GitHubRelease@0
        displayName: Create GitHub Release
        inputs:
          gitHubConnection: github.com_duuwhang
          repositoryName: duuwhang/TurnTimer
          action: create
          target: '$(Build.SourceVersion)'
          tagSource: manual
          tagPattern: 'Git tag'
          tag: '$(Version)'
          title: 'TurnTimer Version $(Version)'
          assets: '$(Root)$(ReleaseDirectory)/*.apk'
          #releaseNotesSource: 'file' # Optional. Options: file, input
          #releaseNotesFile: # Optional
          #releaseNotes: # Optional
