name: $(Rev:_r)

jobs:
  - job: AndroidTestCIPipeline
    timeoutInMinutes: 25
    steps:
      - checkout: self
        displayName: Checkout GitHub Repository
        clean: true
        persistCredentials: true

      - task: Gradle@2
        displayName: Gradle Build Debug APK
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleDebug'

      - bash: |
          set -o xtrace
          $ANDROID_HOME/tools/bin/sdkmanager --list
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-30;google_apis;x86'
        displayName: 'install Android image'

      - bash: |
          set -o xtrace
          $ANDROID_HOME/emulator/emulator -list-avds
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n uitest_android_emulator -k 'system-images;android-30;google_apis;x86' --force
          $ANDROID_HOME/emulator/emulator -list-avds
        displayName: 'create AVD'

      - bash: |
          set -o xtrace
          $ANDROID_HOME/platform-tools/adb devices
          nohup $ANDROID_HOME/emulator/emulator -avd uitest_android_emulator -no-snapshot -no-boot-anim -gpu auto -qemu > /dev/null 2>&1 &
        displayName: 'start Android emulator'

      - bash: |
          set -o xtrace
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
        displayName: 'wait for Android emulator'
        timeoutInMinutes: 5

      # have to run nunit3-console directly; as of 2020-12-17, even though "dotnet
      # run" works with Mono to run .net framework projects, "dotnet test" does not
      # work the same project; see open issue https://github.com/mono/mono/issues/6984
      - pwsh: |
          Set-PSDebug -Trace 1
          $env:UITEST_APK_PATH = "$(Root)$(ReleaseDirectory)/"
          $testAssemblies = Get-Item "$(Build.SourcesDirectory)/TurnTimer.UITest/bin/Release/TurnTimer.UITest*.dll"
          nunit3-console $testAssemblies --output="$(Build.ArtifactStagingDirectory)/uitest.log" --result="$(Build.ArtifactStagingDirectory)/uitest_result.xml"
        displayName: 'run android emulator ui tests'
        continueOnError: true
        timeoutInMinutes: 120

      - script: |
          echo "##vso[task.setvariable variable=ReleaseVersion;isOutput=true]`grep 'versionName' $(Root)/app/build.gradle | tr '"' ' ' | tr 'versionName' ' '| sed 's/ //g'`"
        displayName: Read Release Version
        name: ReadReleaseVersion

  - job: AndroidReleaseCDPipeline
    timeoutInMinutes: 10
    dependsOn: AndroidTestCIPipeline
    variables:
      Version: $[ dependencies.AndroidTestCIPipeline.outputs['ReadReleaseVersion.ReleaseVersion'] ]
      Condition: $[ counter(variables['Version'], 0) ]

    steps:
      - script: |
          echo "##vso[build.updatebuildnumber]$(Version)_$(Condition)"
        displayName: Update Run Name

      - checkout: self
        displayName: Checkout GitHub Repository
        condition: eq(variables['Condition'], 0)
        clean: true
        persistCredentials: true

      - task: Gradle@2
        displayName: Gradle Build Release APK
        condition: eq(variables['Condition'], 0)
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleRelease'

      - task: AndroidSigning@2
        displayName: Sign APK
        condition: eq(variables['Condition'], 0)
        inputs:
          apkFiles: '$(Root)$(ReleaseDirectory)/*.apk'
          jarsign: true
          jarsignerKeystoreFile: 'duu_whang_keystore.keystore'
          jarsignerKeystorePassword: '$(Release.Keystore.Password)'
          jarsignerKeystoreAlias: 'duu_whang_release_key'
          jarsignerKeyPassword: '$(Release.Key.Password)'
          jarsignerArguments: '-verbose -sigalg SHA256withECDSA'
          zipalign: true

      - task: CopyFiles@2
        displayName: Copy APK to Root
        condition: eq(variables['Condition'], 0)
        inputs:
          sourceFolder: '$(Root)$(ReleaseDirectory)/'
          Contents: '*.apk'
          TargetFolder: '$(Root)/'
          OverWrite: true

      - script: |
          git config user.email "maxipulstorm@aon.at"
          git config user.name "duuwhang"
          git checkout master
          git add .
          git commit -m "CD commit"
          git push origin
          git tag $(Version)
          git push origin --tags
        displayName: Commit APK to GitHub Repository
        condition: eq(variables['Condition'], 0)

      - task: GitHubRelease@0
        displayName: Create GitHub Release
        condition: eq(variables['Condition'], 0)
        inputs:
          gitHubConnection: github.com_duuwhang
          repositoryName: duuwhang/TurnTimer
          action: create
          target: '$(Build.SourceVersion)'
          tagSource: manual
          tagPattern: 'Git tag'
          tag: '$(Version)'
          title: 'TurnTimer Version $(Version)'
          assets: '$(Root)$(ReleaseDirectory)/*.apk'
          #releaseNotesSource: 'file' # Optional. Options: file, input
          #releaseNotesFile: # Optional
          #releaseNotes: # Optional
