trigger:
  - manual

variables:
- name: two
  value: initialValue

steps:
  - checkout: self
    persistCredentials: true
    clean: true
    displayName: Checkout GitHub Repository

  - bash: foo="2012"
          echo $foo
          echo "##vso[task.setvariable variable=two;isOutput=true]$foo"
    displayName: Bash
    name: FooStep

  - bash: echo $(FooStep.two)
    displayName: Commit Apk2

  - task: GitHubRelease@0
    displayName: Create GitHub Release
    inputs:
      gitHubConnection: github.com_duuwhang
      repositoryName: TurnTimer
      action: create
      target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: auto
      tagPattern: 'Git tag' # Optional
      #tag: 'V0.002' # Required when action == Edit || Action == Delete || TagSource == Manual
      #title: # Optional
      #releaseNotesSource: 'file' # Optional. Options: file, input
      #releaseNotesFile: # Optional
      #releaseNotes: # Optional
      #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
      #assetUploadMode: 'delete' # Optional. Options: delete, replace
      #isDraft: false # Optional
      #isPreRelease: false # Optional
      #addChangeLog: true # Optional
      #compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
      #releaseTag: # Required when compareWith == LastReleaseByTag
