trigger:
  - manual

jobs:
  - job: Job1
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        displayName: Checkout GitHub Repository

      - script: while read line; do echo $line; done < build.gradle

