trigger:
  - manual

jobs:
  - job: Job1
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        displayName: Checkout GitHub Repository

      - script: echo `grep 'versionName' $(Root)app/build.gradle | tr '"' ' ' | tr 'versionName' ' '`

